In [1]:
import pandas as pd

from control_totals.util import Pipeline

p = Pipeline('configs')

In [2]:
p.get_table('extrapolated_targets')

FileNotFoundError: ``C:\Users\JKolberg\PythonProjects\PSRC\control_totals\examples\legacy_no_R\data\pipeline.h5`` does not exist

In [3]:
with pd.HDFStore("data/pipeline.h5") as store:
    tables = store.keys()
tables

['/adjusted_emp_change_targets_calculations',
 '/adjusted_emp_change_targets_no_res_con',
 '/adjusted_emp_change_targets_res_con',
 '/adjusted_king_targets',
 '/adjusted_total_pop_change_targets',
 '/adjusted_units_change_targets',
 '/block_2010_control_area_xwalk',
 '/block_control_area_xwalk',
 '/blocks',
 '/blocks_2010',
 '/control_areas',
 '/control_target_xwalk',
 '/control_totals',
 '/dec_block_data',
 '/decennial_by_control_area',
 '/employment_2018_by_control_area',
 '/employment_2019_by_control_area',
 '/employment_2020_by_control_area',
 '/extrapolated_targets',
 '/king_targets',
 '/kitsap_targets',
 '/ofm_block_2019',
 '/ofm_block_2019_by_control_area',
 '/ofm_parcel_control_area_xwalk',
 '/ofm_parcelized_2018',
 '/ofm_parcelized_2018_by_control_area',
 '/ofm_parcelized_2019',
 '/ofm_parcelized_2019_by_control_area',
 '/ofm_parcelized_2020',
 '/ofm_parcelized_2020_by_control_area',
 '/parcel_pts_ofm',
 '/pierce_targets',
 '/ref_projection',
 '/snohomish_targets',
 '/target_rgid_xwalk']

In [2]:
p.get_table('split_hct_base_data_2020')

,county_id,nosplit_geo_id,name,split_geo_id,RGID,households,persons,jobs
0,33,1,Bellevue,1,1,30833.0,82397.0,42265.0
1,33,2,Seattle,2,1,88026.0,208484.0,109348.0
2,33,3,Auburn,3,2,18313.0,50704.0,27248.0
3,33,4,Bothell,4,2,8268.0,20759.0,12415.0
4,33,5,Burien,5,2,11798.0,31290.0,7651.0
...,...,...,...,...,...,...,...,...
206,61,138,Mill Creek,1138,3,2255.0,4808.0,4722.0
207,61,139,Mill Creek MUGA,1139,3,1837.0,5154.0,3227.0
208,61,140,Mountlake Terrace,1140,3,1399.0,3281.0,1797.0
209,61,141,Mukilteo,1141,3,412.0,1042.0,600.0
210,61,142,Mukilteo MUGA,1142,3,659.0,1959.0,1670.0

In [5]:
p.get_table('target_rgid_xwalk')

     target_id             name  county_id  rgid
0            1         Bellevue      53033     1
1            2          Seattle      53033     1
2            3           Auburn      53033     2
3            4          Bothell      53033     2
4            5           Burien      53033     2
..         ...              ...        ...   ...
133        170    Snohomish UGA      53061     5
134        172     Stanwood UGA      53061     5
135        174       Sultan UGA      53061     5
136        175     Woodway MUGA      53061     5
137        176  Snohomish Rural      53061     6

[138 rows x 4 columns]