In [1]:
import pandas as pd

from control_totals.util import Pipeline,get_mysql_engine, get_mysql_config
from control_totals.util.elmer_helpers import read_from_elmer_geo
from control_totals.steps.king_cnty_targets import load_king_input_tables, calc_by_rgid, calc_by_target_area, calc_gq_tot_pop

pipeline = Pipeline('configs')

In [10]:
with pd.HDFStore('data/pipeline.h5') as store:
    tables = store.keys()
    base_data = store['split_hct_base_data_2023']
    emp = store['employment_2023_by_control_area']

In [ ]:
# urbansim 2023 base data jobs
base_data[base_data['nosplit_geo_id'] ==402]

,split_geo_id,nosplit_geo_id,households,persons,jobs,name,RGID
152,402,402,1012.0,3511.0,1239.0,NBK - Bangor,6

In [ ]:
# Employment 2023 total from QCEW
emp[emp['control_id'] == 402]

,control_id,control_name,Emp_TotNoMil,Emp_ConRes,Emp_Military,Emp_Total,TotEmpNoMil-ResCon
152,402,NBK - Bangor,4908,10,3071,7979,4898

In [ ]:
# urbansim 2023 base data jobs total
int(base_data['jobs'].sum())

2274414

In [ ]:
# Employment 2023 total from QCEW
int(emp['Emp_TotNoMil'].sum())

2335196

In [ ]:
# difference
int(emp['Emp_TotNoMil'].sum() - base_data['jobs'].sum())

60782

np.int64(2381442)

In [6]:
tables

['/adjusted_emp_change_targets',
 '/adjusted_emp_change_targets_no_res_con',
 '/adjusted_emp_change_targets_res_con',
 '/adjusted_king_targets',
 '/adjusted_total_pop_change_targets',
 '/adjusted_units_change_targets',
 '/annual_employment_control_totals',
 '/annual_employment_control_totals_region',
 '/annual_household_control_totals',
 '/annual_household_control_totals_region',
 '/block_control_area_xwalk',
 '/blocks',
 '/borrow_distribution',
 '/control_areas',
 '/control_hct',
 '/control_target_xwalk',
 '/control_totals',
 '/current_parcel_control_area_xwalk',
 '/dec_block_data',
 '/decennial_by_control_area',
 '/employment_2018_by_control_area',
 '/employment_2019_by_control_area',
 '/employment_2020_by_control_area',
 '/employment_2023_by_control_area',
 '/extrapolated_targets',
 '/king_targets',
 '/kitsap_targets',
 '/ofm_parcel_control_area_xwalk',
 '/ofm_parcelized_2018',
 '/ofm_parcelized_2018_by_control_area',
 '/ofm_parcelized_2019',
 '/ofm_parcelized_2019_by_control_area',
 '/ofm_parcelized_2020',
 '/ofm_parcelized_2020_by_control_area',
 '/ofm_parcelized_2023',
 '/ofm_parcelized_2023_by_control_area',
 '/parcel_pts_current',
 '/parcel_pts_ofm',
 '/pierce_targets',
 '/rebased_control_totals_emp',
 '/rebased_control_totals_hh',
 '/rebased_control_totals_hhpop',
 '/rebased_control_totals_pop',
 '/rebased_control_totals_unrolled',
 '/rebased_control_totals_unrolled_regional',
 '/rebased_targets_city_emp',
 '/rebased_targets_city_hh',
 '/rebased_targets_city_pop',
 '/rebased_targets_rgs',
 '/ref_projection',
 '/regionalCTs_emp',
 '/regionalCTs_hh',
 '/regional_CTs_emp',
 '/regional_CTs_hh',
 '/snohomish_targets',
 '/split_ct_check',
 '/split_ct_emp',
 '/split_ct_emp_work',
 '/split_ct_hh',
 '/split_ct_hh_work',
 '/split_ct_hhpop',
 '/split_ct_hhpop_work',
 '/split_ct_unrolled',
 '/split_ct_unrolled_regional',
 '/split_hct_base_data_2023',
 '/subreg_hh_by_pph_2023',
 '/subreg_mean_pph_2023',
 '/subreg_mean_pph_county_2023',
 '/subregionalCTs_emp',
 '/subregionalCTs_hh']