In [35]:
import pandas as pd

from control_totals.util import Pipeline
from control_totals.util.elmer_helpers import read_from_elmer_geo
from control_totals.steps.king_cnty_targets import load_king_input_tables, calc_by_rgid, calc_by_target_area, calc_gq_tot_pop

p = Pipeline('configs')

In [32]:
with pd.HDFStore('data/pipeline.h5') as store:
    df = store['/extrapolated_targets']
    ofm_2019 = store['/ofm_parcelized_2019_by_control_area']
    ofm_2020 = store['/ofm_parcelized_2020_by_control_area']
    ofm_2023 = store['/ofm_parcelized_2023_by_control_area']
    dec = store['/decennial_by_control_area']
    tables = store.keys()
tables

['/adjusted_emp_change_targets',
 '/adjusted_emp_change_targets_no_res_con',
 '/adjusted_emp_change_targets_res_con',
 '/adjusted_king_targets',
 '/adjusted_total_pop_change_targets',
 '/adjusted_units_change_targets',
 '/block_control_area_xwalk',
 '/blocks',
 '/control_areas',
 '/control_target_xwalk',
 '/control_totals',
 '/current_parcel_control_area_xwalk',
 '/dec_block_data',
 '/decennial_by_control_area',
 '/employment_2018_by_control_area',
 '/employment_2019_by_control_area',
 '/employment_2020_by_control_area',
 '/employment_2023_by_control_area',
 '/extrapolated_targets',
 '/hct_buffers',
 '/hct_stops',
 '/king_targets',
 '/kitsap_targets',
 '/military_bases_xwalk',
 '/ofm_parcel_control_area_xwalk',
 '/ofm_parcelized_2018',
 '/ofm_parcelized_2018_by_control_area',
 '/ofm_parcelized_2019',
 '/ofm_parcelized_2019_by_control_area',
 '/ofm_parcelized_2020',
 '/ofm_parcelized_2020_by_control_area',
 '/ofm_parcelized_2023',
 '/ofm_parcelized_2023_by_control_area',
 '/old_control_areas',
 '/parcel_pts_current',
 '/parcel_pts_ofm',
 '/parcels_hct',
 '/pierce_targets',
 '/psrc_region',
 '/rebased_control_totals_emp',
 '/rebased_control_totals_hh',
 '/rebased_control_totals_hhpop',
 '/rebased_control_totals_pop',
 '/rebased_control_totals_units',
 '/rebased_control_totals_unrolled',
 '/rebased_control_totals_unrolled_regional',
 '/rebased_targets_city_emp',
 '/rebased_targets_city_hh',
 '/rebased_targets_city_pop',
 '/rebased_targets_rgs',
 '/ref_projection',
 '/regional_geographies_xwalk',
 '/snohomish_targets',
 '/split_ct_check',
 '/split_ct_emp',
 '/split_ct_emp_work',
 '/split_ct_hh',
 '/split_ct_hh_work',
 '/split_ct_hhpop',
 '/split_ct_hhpop_work',
 '/split_ct_unrolled',
 '/split_ct_unrolled_regional',
 '/split_hct_base_data_2023',
 '/uga',
 '/urban_centers']

In [34]:
df[['hh_2044','hh_2050']]

           hh_2044  hh_2050
0     92851.000000   101707
1    451849.000000   475447
2     37973.000000    40953
3     17057.000000    18458
4     26922.000000    28888
..             ...      ...
133     694.702262      752
134     184.750169      223
135      85.657036      106
136     134.745947      173
137   52315.320844    53369

[138 rows x 2 columns]

In [14]:
df, ofm = load_king_input_tables(p,'units')
df = df.loc[df['county_id'] == 53033].copy()

In [25]:
df[['hh_2044']]

    hh_2044
0     92851
1    451849
2     37973
3     17057
4     26922
5     46453
6     18731
7     55661
8     50285
9     46903
10    57118
11    16684
12    13948
13    16048
14     9104
15    12078
16     6095
17    11266
18     6469
19     8695
20     2738
21     9380
22     6927
23    35890
24     7376
25     1175
26      115
27     4340
28     1182
29     1061
30    10910
31     3473
32     6200
33      180
34    10661
35     1109
36      629
37     2870
38     5224
39     2510
40    23525
41      155
42     5446
43      417
44       83
45       21
46      370
47      110
48      175
49     1052
50        4
51      427
52     1039
53      362
54     4540
55    51656

In [17]:
targets_rgid = calc_by_rgid(p, df)

In [18]:
targets_rgid.head()

,rgid,units_chg,units_chg_adj,ofm_total_pop,ofm_hhpop,ofm_units,ofm_hh,ofm_gq,ofm_hhpop_by_target,ofm_hh_by_target,ofm_hhsz_by_target,ofm_hhsz,hhsz_2044,vacancy_rate,units_2044,hh_2044,hhpop_initial_2044,hhpop_factored_2044
0,1,147000.0,107304.0,922465.017420,898388.801237,464259.373315,431114.059563,24076.216183,898388.801237,431114.059563,4.481093,4.481093,2.12,4.7,571563.373315,544700,1154764,1148676
1,2,112860.0,96726.0,774774.845694,766559.576185,308854.270223,291816.889555,8215.269509,766559.576185,291816.889555,28.707333,28.707333,2.52,4.4,405580.270223,387735,977092,971941
2,3,29942.0,24855.0,280210.170960,276750.358731,112142.004927,106321.478109,3459.812229,276750.358731,106321.478109,31.671162,31.671162,2.51,3.6,136997.004927,132065,331483,329735
3,4,16353.0,11646.0,202845.347474,202269.347474,72045.807841,68932.094831,576.000000,202269.347474,68932.094831,53.316012,53.316012,2.75,3.0,83691.807841,81181,223248,222071
4,5,1292.0,1053.0,19590.416412,19582.416412,7382.855640,7046.999626,8.000000,19582.416412,7046.999626,47.400522,47.400522,2.65,3.0,8435.855640,8183,21685,21571

In [19]:
df = calc_by_target_area(p, df, targets_rgid)

In [21]:

# perform calculations


df = calc_gq_tot_pop(p, df, ofm)

In [61]:
df[['target_id','units_chg_adj','ofm_units','units_2044']]

    target_id  units_chg_adj      ofm_units     units_2044
0           1        31505.0   65925.616896   97430.616896
1           2        75799.0  398333.756419  474132.756419
2           3        11032.0   28688.404788   39720.404788
3           4         4973.0   12869.444801   17842.444801
4           5         7162.0   20998.794841   28160.794841
5           6        10709.0   37882.372696   48591.372696
6           7         2042.0   17551.225502   19593.225502
7           8         8465.0   49757.419525   58222.419525
8           9        10046.0   42552.921107   52598.921107
9          10        14847.0   34215.064618   49062.064618
10         11        16233.0   43513.443367   59746.443367
11         12         5815.0   11636.753167   17451.753167
12         13         5402.0    9188.425811   14590.425811
13         14         3245.0   13401.934593   16646.934593
14         15          771.0    8673.181733    9444.181733
15         16         2735.0    9794.277581   12529.277581
16         17          816.0    5506.377847    6322.377847
17         18         1087.0   10600.200113   11687.200113
18         19          901.0    5809.897815    6710.897815
19         20         1088.0    7931.937001    9019.937001
20         22          149.0    2690.781227    2839.781227
21         23          652.0    9078.414866    9730.414866
22         24          536.0    6649.177360    7185.177360
23         25        11638.0   25591.824798   37229.824798
24         26         1237.0    6413.999993    7650.999993
25         27          150.0    1061.749822    1211.749822
26         28            1.0     118.000000     119.000000
27         29         1791.0    2682.899975    4473.899975
28         30          279.0     939.721327    1218.721327
29         31           10.0    1083.719527    1093.719527
30         32         3843.0    7404.217907   11247.217907
31         33          521.0    3059.821124    3580.821124
32         34          549.0    5842.454004    6391.454004
33         35            1.0     184.264694     185.264694
34         36         1043.0    9948.011436   10991.011436
35         37            2.0    1140.787394    1142.787394
36         38           50.0     598.053819     648.053819
37         39          114.0    2844.453514    2958.453514
38         40         1227.0    4158.099739    5385.099739
39         41          112.0    2475.499477    2587.499477
40         42         1455.0   22797.599626   24252.599626
41         43           10.0     149.961499     159.961499
42         44          486.0    5128.777990    5614.777990
43         45            2.0     427.714967     429.714967
44         46           12.0      73.123000      85.123000
45         48           17.0       4.982000      21.982000
46         49          328.0      52.964001     380.964001
47         51           33.0      80.622653     113.622653
48         52            3.0     177.814999     180.814999
49         53          371.0     713.545467    1084.545467
50         57            1.0       3.000000       4.000000
51         58          129.0     311.580002     440.580002
52         60          117.0     954.369002    1071.369002
53         61           42.0     330.889004     372.889004
54         62            0.0    4679.965512    4679.965512
55         64         3297.0   51078.082665   54375.082665