In [1]:
import pandas as pd

from control_totals.util import Pipeline
from control_totals.util.db_helpers import read_mysql_creds, get_mysql_engine, get_mysql_config

pipeline = Pipeline('configs')

In [2]:
with pd.HDFStore('data/pipeline.h5') as store:
    tables = store.keys()
    base_data = store['/split_hct_base_data_2023']
    rebased_emp = store['/rebased_control_totals_emp']
    emp_controls = store['/regionalCTs_emp']
    targets = store['/extrapolated_targets']
    pierce_targets = store['/pierce_targets']
    ofm_2023 = store['/ofm_parcelized_2023_by_control_area']

In [3]:
base_data[base_data['name'] == 'Mill Creek']

,split_geo_id,nosplit_geo_id,households,persons,jobs,name,RGID
103,138.0,138.0,5186.0,13463.0,1928.0,Mill Creek,3
200,1138.0,138.0,3910.0,8545.0,5687.0,Mill Creek,3

In [4]:
ofm_2023[ofm_2023['control_id'] == 138]

     control_id  ofm_total_pop     ofm_hhpop   ofm_units       ofm_hh  ofm_gq
103         138   21420.699709  21350.699709  9332.90906  8951.527602    70.0

In [4]:
tables

['/adjusted_emp_change_targets',
 '/adjusted_emp_change_targets_no_res_con',
 '/adjusted_emp_change_targets_res_con',
 '/adjusted_king_targets',
 '/adjusted_total_pop_change_targets',
 '/adjusted_units_change_targets',
 '/block_control_area_xwalk',
 '/blocks',
 '/borrow_distribution',
 '/control_areas',
 '/control_hct',
 '/control_target_xwalk',
 '/control_totals',
 '/current_parcel_control_area_xwalk',
 '/dec_block_data',
 '/decennial_by_control_area',
 '/employment_2018_by_control_area',
 '/employment_2019_by_control_area',
 '/employment_2020_by_control_area',
 '/employment_2023_by_control_area',
 '/extrapolated_targets',
 '/king_targets',
 '/kitsap_targets',
 '/ofm_parcel_control_area_xwalk',
 '/ofm_parcelized_2018',
 '/ofm_parcelized_2018_by_control_area',
 '/ofm_parcelized_2019',
 '/ofm_parcelized_2019_by_control_area',
 '/ofm_parcelized_2020',
 '/ofm_parcelized_2020_by_control_area',
 '/ofm_parcelized_2023',
 '/ofm_parcelized_2023_by_control_area',
 '/parcel_pts_current',
 '/parcel_pts_ofm',
 '/parcels_capacity',
 '/pierce_targets',
 '/rebased_control_totals_emp',
 '/rebased_control_totals_hh',
 '/rebased_control_totals_hhpop',
 '/rebased_control_totals_pop',
 '/rebased_control_totals_unrolled',
 '/rebased_control_totals_unrolled_regional',
 '/rebased_targets_city_emp',
 '/rebased_targets_city_hh',
 '/rebased_targets_city_pop',
 '/rebased_targets_rgs',
 '/ref_projection',
 '/regionalCTs_emp',
 '/regionalCTs_hh',
 '/snohomish_targets',
 '/split_ct_check',
 '/split_ct_emp',
 '/split_ct_emp_work',
 '/split_ct_hh',
 '/split_ct_hh_work',
 '/split_ct_hhpop',
 '/split_ct_hhpop_work',
 '/split_ct_unrolled',
 '/split_ct_unrolled_regional',
 '/split_hct_base_data_2023',
 '/subreg_hh_by_pph_2023',
 '/subreg_mean_pph_2023',
 '/subreg_mean_pph_county_2023',
 '/subregionalCTs_emp',
 '/subregionalCTs_hh']

In [27]:
targets.columns

Index(['target_id', 'total_pop_chg', 'total_pop_chg_adj', 'units_chg',
       'units_chg_adj', 'rgid', 'county_id', 'ofm_total_pop', 'ofm_hhpop',
       'ofm_units', 'ofm_hh', 'ofm_gq', 'ofm_vacancy_by_rgid', 'ofm_gq_pct',
       'gq_2044', 'total_pop_2044', 'hhpop_2044', 'units_2044', 'hh_2044',
       'hhsz_2044', 'king_hhsz', 'vacancy_rate', 'hhpop_initial_2044',
       'initial_hhpop_2044_sum_by_rgid', 'hhpop_rgid_factored_2044',
       'hhpop_factor', 'emp_chg', 'emp_chg_adj', 'control_id_2023',
       'control_name_2023', 'Emp_TotNoMil_2023', 'Emp_ConRes_2023',
       'Emp_Military_2023', 'Emp_Total_2023', 'TotEmpNoMil-ResCon_2023',
       'emp_2044', 'res_con_pct', 'res_con_target_pct', 'emp_chg_cnty_sum',
       'res_con_emp_chg_cnty_sum', 'res_con_emp_chg_target',
       'emp_chg_adj_res_con', 'hh_annual_change', 'hh_2050',
       'total_pop_annual_change', 'total_pop_2050', 'emp_annual_change',
       'emp_2050', 'gq_2050', 'hhpop_2050', 'hhsz_2050'],
      dtype='str')

In [8]:
targets[['target_id','county_id','ofm_units','units_2044','units_chg','units_chg_adj']].to_csv('output/target_test.csv')

In [30]:
targets[['emp_chg','emp_chg_adj']].sum()

emp_chg        850053
emp_chg_adj    790270
dtype: int64

In [17]:
pierce_targets.loc[pierce_targets['target_id'] ==  77]

,target_id,name,Jurisdiction,total_pop_chg,units_chg,emp_chg,county_id
0,77,Tacoma,Tacoma,105977,42865,70800,53053

In [32]:
ofm_2020['Emp_TotNoMil'].sum()

np.int64(2312316)

In [33]:
ofm_2023['Emp_TotNoMil'].sum()

np.int64(2335196)

In [34]:
# urbansim 2023 base data jobs total
base_data['jobs'].sum()

np.float64(2274414.0)

In [5]:
# Employment 2023 total from QCEW
int(emp['Emp_TotNoMil'].sum())

2335196

In [6]:
# difference
int(emp['Emp_TotNoMil'].sum() - base_data['jobs'].sum())

60782

In [7]:
# 2050 emp targets
int(targets['emp_2050'].sum())

3375114

In [8]:
# 2050 after rebased
int(rebased_emp['2050'].sum())

3375114

In [9]:
# 2050 emp control total
int(emp_controls.loc[emp_controls['year'] == 2050,'total_number_of_jobs'].sum())

3375929

In [10]:
# diff
int(rebased_emp['2050'].sum()) - int(emp_controls.loc[emp_controls['year'] == 2050,'total_number_of_jobs'].sum())

-815

In [13]:
db = get_mysql_config(pipeline)
engine = get_mysql_engine(
    '2023_parcel_baseyear', db['creds_path'], user_env=db['user_env'], password_env=db['password_env'], host_env=db['host_env']
)

In [22]:
p_query = f"""
    SELECT parcel_id FROM 2023_parcel_baseyear.parcels
"""
urbansim_p = pd.read_sql_query(p_query, engine)

In [24]:
len(urbansim_p)

1329928

In [25]:
max(urbansim_p['parcel_id'])

1329928

In [26]:
current_p = pipeline.get_geodataframe('parcel_pts_current')

In [27]:
len(current_p)

1329929

In [28]:
max(current_p['parcel_id'])

1329929

In [40]:
cap_path = 'Q:/Projects/2023_Baseyear/FLU_and_Lockouts/capacity/CapacityPclFLU_res50_flu-2026-09-30_2026-10-05.csv'
cap = pd.read_csv(cap_path)

In [44]:
len(cap.loc[cap['subreg_id'] == 1138])

602

In [57]:
xwalk_path = "Q:/Projects/2023_Baseyear/Political/control_geographies/parcels_control_hct_xwalk_2026-10-13.csv"
xwalk = pd.read_csv(xwalk_path)

In [58]:
len(xwalk.loc[xwalk['subreg_id'] == 1138])

1145

In [59]:
xwalk.dtypes

parcel_id         int64
rural             int64
urban_center      int64
srt               int64
lrt               int64
mrt               int64
crt               int64
fry               int64
pof               int64
brt               int64
tod               int64
control_id        int64
rgid              int64
control_hct_id    int64
subreg_id         int64
target_id         int64
county_id         int64
dtype: object

In [60]:
xwalk.loc[xwalk['rgid'].isna()]

Empty DataFrame
Columns: [parcel_id, rural, urban_center, srt, lrt, mrt, crt, fry, pof, brt, tod, control_id, rgid, control_hct_id, subreg_id, target_id, county_id]
Index: []

In [51]:
xwalk.to_csv(xwalk_path, index=False)